export const imageUrls = [
  "https://images.unsplash.com/photo-1506744038136-46273834b3fb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
  "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
  "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
  "https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
  "https://images.unsplash.com/photo-1475924156734-496f6cac6ec1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
  "https://images.unsplash.com/photo-1494500764479-0c8f2919a3d8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
  "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
  "https://images.unsplash.com/photo-1551963831-b3b1ca40c98e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
];

export const userData = [
  { id: 1, name: "Alice Johnson", email: "alice.johnson@example.com" },
  { id: 2, name: "Bob Smith", email: "bob.smith@example.com" },
  { id: 3, name: "Carol Williams", email: "carol.williams@example.com" },
  { id: 4, name: "David Brown", email: "david.brown@example.com" },
  { id: 5, name: "Emily Davis", email: "emily.davis@example.com" },
  { id: 6, name: "Frank Miller", email: "frank.miller@example.com" },
  { id: 7, name: "Grace Wilson", email: "grace.wilson@example.com" },
  { id: 8, name: "Henry Jones", email: "henry.jones@example.com" },
  { id: 9, name: "Isabella Taylor", email: "isabella.taylor@example.com" },
  { id: 10, name: "Jack Anderson", email: "jack.anderson@example.com" },
  { id: 11, name: "Katherine Thomas", email: "katherine.thomas@example.com" },
  { id: 12, name: "Liam Moore", email: "liam.moore@example.com" },
  { id: 13, name: "Mia Jackson", email: "mia.jackson@example.com" },
  { id: 14, name: "Noah White", email: "noah.white@example.com" },
  { id: 15, name: "Olivia Harris", email: "olivia.harris@example.com" },
  { id: 16, name: "Peter Martin", email: "peter.martin@example.com" },
  { id: 17, name: "Quinn Thompson", email: "quinn.thompson@example.com" },
  { id: 18, name: "Ryan Clark", email: "ryan.clark@example.com" },
  { id: 19, name: "Sophia Lewis", email: "sophia.lewis@example.com" },
  { id: 20, name: "Thomas Walker", email: "thomas.walker@example.com" },
];

export const questions = [
  {
    id: 1,
    question: "What is the capital of France?",
    options: ["London", "Paris", "Berlin", "Rome"],
    answer: "Paris",
    category: "Geography",
    difficulty: "Easy",
    explanation: "Paris is the capital and most populous city of France.",
  },
  {
    id: 2,
    question: "Who wrote the play 'Romeo and Juliet'?",
    options: [
      "William Shakespeare",
      "Charles Dickens",
      "Jane Austen",
      "Mark Twain",
    ],
    answer: "William Shakespeare",
    category: "Literature",
    difficulty: "Easy",
    explanation:
      "William Shakespeare is the renowned playwright who wrote 'Romeo and Juliet', a tragic love story.",
  },
  {
    id: 3,
    question: "What is the largest planet in our solar system?",
    options: ["Earth", "Mars", "Jupiter", "Venus"],
    answer: "Jupiter",
    category: "Science",
    difficulty: "Easy",
    explanation:
      "Jupiter is a gas giant and the largest planet in our solar system.",
  },
  {
    id: 4,
    question: "In what year did World War I begin?",
    options: ["1914", "1918", "1939", "1945"],
    answer: "1914",
    category: "History",
    difficulty: "Medium",
    explanation: "World War I began in 1914 and ended in 1918.",
  },
  {
    id: 5,
    question: "Who painted the ceiling of the Sistine Chapel?",
    options: ["Leonardo da Vinci", "Michelangelo", "Raphael", "Caravaggio"],
    answer: "Michelangelo",
    category: "Art",
    difficulty: "Medium",
    explanation:
      "Michelangelo, a famous Renaissance artist, painted the ceiling of the Sistine Chapel in Vatican City.",
  },
  {
    id: 6,
    question: "What is the chemical symbol for water?",
    options: ["H2O", "CO2", "O2", "NaCl"],
    answer: "H2O",
    category: "Science",
    difficulty: "Easy",
    explanation:
      "The chemical formula for water is H2O, representing two hydrogen atoms and one oxygen atom.",
  },
  {
    id: 7,
    question: "Who is the author of the 'Lord of the Rings' trilogy?",
    options: [
      "J.R.R. Tolkien",
      "C.S. Lewis",
      "George R.R. Martin",
      "J.K. Rowling",
    ],
    answer: "J.R.R. Tolkien",
    category: "Literature",
    difficulty: "Medium",
    explanation:
      "J.R.R. Tolkien wrote the epic high fantasy novel 'The Lord of the Rings'.",
  },
  {
    id: 8,
    question: "What is the currency of Japan?",
    options: ["Dollar", "Euro", "Pound", "Yen"],
    answer: "Yen",
    category: "Geography",
    difficulty: "Easy",
    explanation: "The Japanese Yen (JPY) is the official currency of Japan.",
  },
  {
    id: 9,
    question: "What is the name of the highest mountain in Africa?",
    options: [
      "Mount Kilimanjaro",
      "Mount Kenya",
      "Mount Stanley",
      "Mount Meru",
    ],
    answer: "Mount Kilimanjaro",
    category: "Geography",
    difficulty: "Medium",
    explanation:
      "Mount Kilimanjaro is a dormant volcano in Tanzania and the highest mountain in Africa.",
  },
  {
    id: 10,
    question: "Who discovered the theory of relativity?",
    options: [
      "Isaac Newton",
      "Galileo Galilei",
      "Albert Einstein",
      "Stephen Hawking",
    ],
    answer: "Albert Einstein",
    category: "Science",
    difficulty: "Medium",
    explanation:
      "Albert Einstein developed the theory of relativity, one of the two pillars of modern physics.",
  },
  {
    id: 11,
    question: "What is the smallest prime number?",
    options: ["0", "1", "2", "3"],
    answer: "2",
    category: "Mathematics",
    difficulty: "Easy",
    explanation:
      "A prime number is a whole number greater than 1 whose only factors are 1 and itself. 2 is the smallest prime number.",
  },
  {
    id: 12,
    question: "Who is the Greek god of thunder?",
    options: ["Zeus", "Poseidon", "Hades", "Ares"],
    answer: "Zeus",
    category: "Mythology",
    difficulty: "Easy",
    explanation:
      "Zeus is the sky and thunder god in ancient Greek religion, who rules as king of the gods on Mount Olympus.",
  },
  {
    id: 13,
    question: "What is the chemical symbol for silver?",
    options: ["Au", "Ag", "Si", "Fe"],
    answer: "Ag",
    category: "Science",
    difficulty: "Easy",
    explanation:
      "The chemical symbol for silver is Ag, derived from the Latin word 'argentum'.",
  },
  {
    id: 14,
    question: "Who directed the movie 'Jurassic Park'?",
    options: [
      "Steven Spielberg",
      "George Lucas",
      "James Cameron",
      "Quentin Tarantino",
    ],
    answer: "Steven Spielberg",
    category: "Movies",
    difficulty: "Easy",
    explanation:
      "Steven Spielberg directed the 1993 science fiction adventure film 'Jurassic Park'.",
  },
  {
    id: 15,
    question: "What is the capital of Australia?",
    options: ["Sydney", "Melbourne", "Canberra", "Brisbane"],
    answer: "Canberra",
    category: "Geography",
    difficulty: "Medium",
    explanation: "Canberra is the capital city of Australia.",
  },
];
